from __future__ import annotations

from datetime import date
from typing import Any

from planset_manifest import build_plan_set_manifest
from planset_auto_page_emitters import emit_auto_page_entities
from planset_site_page_profiles import get_site_page_profile


_SITE_AUTO_PAGES = {1, 2, 4, 5, 6, 7, 12, 13, 16, 17, 42, 43}


def _normalized_inputs(payload: dict[str, Any]) -> dict[str, Any]:
    normalized = payload.get("normalized_inputs")
    if isinstance(normalized, dict):
        return normalized
    return {}


def _build_default_sheet_metadata(page_number: int) -> dict[str, Any]:
    site_profile = get_site_page_profile(page_number)
    sheet_title = f"Sheet {page_number}"
    if isinstance(site_profile, dict):
        profile_title = site_profile.get("sheet_title")
        if isinstance(profile_title, str) and profile_title.strip():
            sheet_title = profile_title.strip()

    return {
        "sheet_number": str(page_number).zfill(2),
        "sheet_title": sheet_title,
        "discipline": "Electrical",
        "scale": "NTS",
        "revision": "A",
        "issue_date": date.today().isoformat(),
        "north_arrow": page_number in {1, 2, 4, 5, 6, 7, 12, 13, 16, 17, 42, 43},
    }


def _build_default_title_block(payload: dict[str, Any]) -> dict[str, Any]:
    normalized = _normalized_inputs(payload)
    project_metadata = normalized.get("project_metadata") if isinstance(normalized.get("project_metadata"), dict) else {}

    title_block = payload.get("title_block")
    if isinstance(title_block, dict):
        return {
            "project_name": str(title_block.get("project_name", "Untitled Project")),
            "client_name": str(title_block.get("client_name", "Unknown Client")),
            "site_name": str(title_block.get("site_name", "Unknown Site")),
            "site_address": str(title_block.get("site_address", "")),
            "project_number": str(title_block.get("project_number", "")),
            "drawn_by": str(title_block.get("drawn_by", "CADream")),
            "checked_by": str(title_block.get("checked_by", "")),
            "approved_by": str(title_block.get("approved_by", "")),
            "company_name": str(title_block.get("company_name", "")),
        }

    designer = project_metadata.get("designer") if isinstance(project_metadata.get("designer"), dict) else {}
    sheet_defaults = (
        project_metadata.get("sheet_defaults") if isinstance(project_metadata.get("sheet_defaults"), dict) else {}
    )

    if project_metadata:
        return {
            "project_name": str(project_metadata.get("project_name", "Untitled Project")),
            "client_name": str(project_metadata.get("client_name", "Unknown Client")),
            "site_name": str(project_metadata.get("site_address", "Unknown Site")),
            "site_address": str(project_metadata.get("site_address", "")),
            "project_number": "",
            "drawn_by": str(sheet_defaults.get("drawn_by", "CADream")),
            "checked_by": str(sheet_defaults.get("checked_by", "")),
            "approved_by": str(sheet_defaults.get("approved_by", "")),
            "company_name": str(designer.get("company", "")),
        }

    return {
        "project_name": "Untitled Project",
        "client_name": "Unknown Client",
        "site_name": "Unknown Site",
        "site_address": "",
        "project_number": "",
        "drawn_by": "CADream",
        "checked_by": "",
        "approved_by": "",
        "company_name": "",
    }


def _build_auto_stub(page_number: int, requirements: list[str], payload: dict[str, Any]) -> dict[str, Any]:
    generated_entities = emit_auto_page_entities(payload, page_number)

    notes = [
        "Stub payload generated by /planset/payload-stubs.",
    ]

    if page_number in _SITE_AUTO_PAGES:
        notes.append("Site-driven auto-page emitter applied shared geometry/layer/annotation services.")
    if page_number in {24, 25}:
        notes.append("SLD-driven auto-page emitter applied shared geometry/layer/annotation services.")

    return {
        "schema_version": "auto-page-payload-v1",
        "generation_mode": "auto",
        "page_number": page_number,
        "generator": {
            "name": "planset-orchestrator-stub",
            "version": "v1",
        },
        "sheet_metadata": _build_default_sheet_metadata(page_number),
        "title_block": _build_default_title_block(payload),
        "inputs_used": sorted(set(requirements + ["cad_ir"])),
        "content": {
            "entities": generated_entities,
            "notes": notes,
        },
    }


def _build_fixed_stub(page_number: int, payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": "fixed-page-payload-v1",
        "generation_mode": "fixed",
        "page_number": page_number,
        "template": {
            "template_id": f"page-{str(page_number).zfill(2)}-template",
            "include_strategy": "overlay_metadata",
            "source_path": f"templates/page-{str(page_number).zfill(2)}.dxf",
        },
        "sheet_metadata": _build_default_sheet_metadata(page_number),
        "title_block": _build_default_title_block(payload),
    }


def build_plan_set_payload_stubs(payload: dict[str, Any]) -> dict[str, Any]:
    manifest = build_plan_set_manifest(payload)

    page_payloads: list[dict[str, Any]] = []
    for page in manifest["pages"]:
        page_number = int(page["page_number"])
        status = str(page["status"])
        requirements = list(page.get("requirements", []))

        if status == "auto":
            page_payloads.append(
                {
                    "page_number": page_number,
                    "status": status,
                    "payload_schema": "auto-page-payload-v1",
                    "payload": _build_auto_stub(page_number, requirements, payload),
                }
            )
            continue

        if status == "fixed":
            page_payloads.append(
                {
                    "page_number": page_number,
                    "status": status,
                    "payload_schema": "fixed-page-payload-v1",
                    "payload": _build_fixed_stub(page_number, payload),
                }
            )
            continue

        page_payloads.append(
            {
                "page_number": page_number,
                "status": "pending",
                "payload_schema": None,
                "payload": None,
                "missing_reasons": page.get("missing_reasons", []),
            }
        )

    return {
        "schema_version": "planset-payload-stubs-v1",
        "manifest": manifest,
        "page_payloads": page_payloads,
    }
