export const CAD_HEAVY_SCENE_VISIBLE_ENTITY_THRESHOLD = 15000;
export const CAD_HEAVY_SCENE_DOC_ENTITY_THRESHOLD = 20000;
export const CAD_SCENE_HEAVY_MODE_ENTITY_THRESHOLD = 12000;

export const CAD_ARC_PIXELS_PER_SEGMENT_HEAVY = 20;
export const CAD_ARC_PIXELS_PER_SEGMENT_LIGHT = 10;
export const CAD_ARC_MAX_SEGMENTS_HEAVY = 128;
export const CAD_ARC_MAX_SEGMENTS_LIGHT = 512;

export const CAD_TEXT_MAX_RENDER_HEIGHT = 200;
export const CAD_TEXT_MIN_RENDER_SIZE = 8;
export const CAD_TEXT_MAX_RENDER_SIZE = 28;

export const CAD_STATIC_STROKE_WIDTH = 1;
export const CAD_INSERT_MARKER_SIZE = 60;
export const CAD_INSERT_FALLBACK_MARKER_SIZE = 12;
export const CAD_INSERT_FALLBACK_STROKE_WIDTH = 2;
export const CAD_INSERT_FALLBACK_LABEL_SIZE = 12;
export const CAD_INSERT_MIN_VISIBLE_PIXEL_SIZE = 0.7;
export const CAD_MAX_INSERT_RECURSION_DEPTH = 10;
